version: '3.8'

services:
  backend:
    build: ./backend  # Path to Dockerfile
    ports:
      - "8080:8080"  # Maps container port 8080 to localhost:8080
    env_file:
      - backend/.env  # Load environment variables
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: Ambaks
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: campuseats
    ports:
      - "5432:5432"  # Maps container port 5432 to localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: